src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="text")
     */
    private $Image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Notes;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->Notes;
    }

    public function setNotes(?string $Notes): self
    {
        $this->Notes = $Notes;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 *  fields = {"email"},
 *  message = "L'email est déjà utilisé !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8", minMessage="Votre mdp doit faire minimum 8 caractères !")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password")
     */
    public $confirm_password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $roles;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles() {
        return ['ROLE_USER'];
    }

    public function setRoles(?string $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    
    public function eraseCredentials() {

    }

    public function getSalt() {

    }

}

src/Form/RegistrationType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username')
            ->add('email')
            ->add('password', PasswordType::class)
            ->add('confirm_password', PasswordType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/MusicController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MusicController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        
        $repo = $this->getDoctrine()->getRepository(Film::class);
        $films = $repo->findAll();
        return $this->render('music/index.html.twig', [
            'controller_name' => 'MusicController',
            'films' => $films
        ]);
    }

    /**
     * @Route("/about", name="about")
     */
    public function about()
    {
        return $this->render('music/about.html.twig', [
            'controller_name' => 'MusicController',
        ]);
    }

    /**
     * @Route("/film/{id}", name="film_show")
     */
    public function film_show(Film $film)
    {
        return $this->render('music/film_show.html.twig', [
            'controller_name' => 'MusicController',
            'film' => $film
        ]);
    }

    /**
     * @Route("/film/{id}/edit", name="film_edit")
     * @Route("/films/add", name="film_new")
     */
    public function film_mod(Film $film = null, Request $request, EntityManagerInterface $manager)
    {
        if(!$film){
        $film = new Film();
    }

    $form = $this->createFormBuilder($film)
        ->add('name', TextType::class, [
            'attr' => [
                'placeholder' => 'Nom film'
            ]
        ])
        ->add('description', TextareaType::class, [
            'attr' => [
                'placeholder' => 'Description film'
            ]
        ])
        ->add('image', TextType::class, [
            'attr' => [
                'placeholder' => 'Lien image plat'
            ]
        ])
        ->getForm();
    
    $form->handleRequest($request);

    if($form->isSubmitted() && $form->isValid()) {
        $manager->persist($film);
        $manager->flush();

        return $this->redirectToRoute('film_show', ['id' => $film->getId()]);
    }
        return $this->render('music/film_mod.html.twig', [
        'formfilm' => $form->createView(),
        'editMode' => $film->getId() !== null
    ]);
}

    /**
     * @Route("/film/{id}/del", name="film_del")
     */
    public function film_del(Film $film, EntityManagerInterface $manager)
    {
        $manager->remove($film);
        $manager->flush();
        return $this->redirectToRoute('index', [
            'film' => $film
        ]);
    }
}

    
    

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/register", name="user_register")
     */
    public function inscript(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder) 
    {
        $user = new User();

        $form = $this->createForm(RegistrationType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user, $user->getPassword());

            $user->setPassword($hash);

            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('user_login');
        }

        return $this->render('security/index.html.twig', [
            'form' => $form->createView()
        ]);
    }
    
    /**
     * @Route("/login", name="user_login")
     */
    public function login(){
        return $this->render('security/login.html.twig');
    }

    /**
     * @Route("/logout", name="user_logout")
     */
    public function user_logout(){}

}

templates/base.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>
      {% block title %}
        Movie
      {% endblock %}
    </title>
    {% block stylesheets %}
    <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css">
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">MovieFilms</a>
        <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarColor02"
          aria-controls="navbarColor02"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">
                Accueil <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item"><a class="nav-link" href="#">Inscription</a></li>
            <li class="nav-item"><a class="nav-link" href="{{path('about')}}">A propos</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Gestion des utilisateurs</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Gestion des films</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Dashboard</a></li>
                {% if not app.user %}
            <li class="nav-item"><a class="nav-link" href="{{path('user_register')}}">Inscription</a></li>
            <li class="nav-item"><a class="nav-link" href="{{path('user_login')}}">Connexion</a></li>
                {% else %}
            <li class="nav-item"><a class="nav-link" href="{{path('user_logout')}}">Déconnexion</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    {% block body %}
    {% endblock %}
    {% block javascripts %}
    {% endblock %}
  </body>
</html>

templates/music/about.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<br>
<h2 class="mx-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque voluptatem doloribus, ea nobis aliquid omnis.</h2>
<br>
<h2 class="mx-5">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia blanditiis odio maiores? Perspiciatis, libero id.</h2>
{% endblock %}

templates/music/film_mod.html.twig
{% extends 'base.html.twig' %}

{% form_theme formfilm 'bootstrap_4_layout.html.twig' %}

{% block body %}
  <br /><br />
  <h1 class="text-center">
        {% if editMode %}
            Modifications
        {% else %}
            Création de film
        {% endif %}
  </h1>
  <br /><br />

  <div class="text-center row">
    <div class="col"></div>
    <div class="col">
      {{ form_start(formfilm) }}

      {{ form_widget(formfilm) }}
        
      <button type="submit" class="btn btn-lg btn-secondary">
        {% if editMode %}
            Enregistrer les modifications
        {% else %}
            Ajouter le plat
        {% endif %}
      </button>

      {{ form_end(formfilm) }}
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/music/film_show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<br>
<h1 class="text-center">{{film.name}}</h1>
<hr><br>
<div class="row">
    <div class="col w-25">
        <img src="{{film.image}}" alt="{{film.name}}">
    </div>
    <div class="col w-75">
        <br><br><br>
        <h2>{{film.description}}</h2>
    </div>
    <div class="col"></div>
</div>
<br><br>
<h1 class="float-left">Notes : {{film.notes}} / 5</h1>
<br><br><br><br>
<h1 class="float-left">Commentaires :</h1>
<br><br><br>
{# Mettre un if admin #}
<a href="{{ path('film_edit', {'id':film.id}) }}" class="btn btn-secondary">Editer</a>
<a href="{{ path('film_del', {'id':film.id}) }}" class="btn btn-secondary">Supprimer</a>
{% endblock %}

templates/music/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class='mx-5'> 
    <br><hr><br>
    <h1>Liste des films</h1>
    <br><br>
    {% for film in films %}
    <div class="row mx-5">
        <div class="col">
            <a href="{{path('film_show', {'id':film.id})}}" class="text-center">
                <h2 class="row">{{film.Name}}</h2>
                <br>
                <img src="{{film.image}}" alt="{{film.Name}}" class="float-left text-center">
                <h3 class="float-right">{{film.description}}</h3>
                <br>
                <h3 class="row">
                    {{film.notes}} Etoiles / 5
                </h3>
            </a>
        </div>
    </div>
    <br><hr><br>
    {% endfor %}
</div>
{% endblock %}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Inscription
{% endblock %}

{% block body %}
  <br /><br /><br />
  <div class="text-center row">
    <div class="col"></div>
    <div class="col">
      <h1>
        Inscription
      </h1>

      {{ form_start(form) }}
      {{ form_widget(form) }}
      <button type="submit" class="btn btn-lg btn-secondary">
        S'inscrire
      </button>
      {{ form_end(form) }}
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<br><br>
<div class="text-center row">
    <div class="col"></div>
    <h1 class="col">Connexion</h1>
    <div class="col"></div>
</div>
<br><br>
<div class="text-center row">
    <div class="col"></div>
    <div class="col">
        <form action="{{path('user_login') }}" method="post">
            <div class="form-group">
                <input placeholder="Email" required name="_username" type="text" class="form-control">
            </div>
            <div class="form-group">
                <input placeholder="Password" required name="_password" type="password" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-secondary">Connexion</button>
            </div>
        </form>
    </div>
    <div class="col"></div>
</div>
    
{% endblock %}